### PR TITLE
Set current unix timestamp as version number

### PR DESCRIPTION
**Pull request by mlieser**

### CODE REVIEW

**Comment by lucaspinto** [comment]
Why this change? Why not leave the commit sha?

**Comment by mlieser** [comment]
If the version number is not explicitly set, BOSH simply increases this each time. This means, if the current final version number for the name foobar-sha1 is 5 and the current dev version number is 3 (foobar-sha1-5+dev.3.yml), the next dev version number will be 4 (foobar-sha1-5+dev.4.yml).
    The problem here is that the dev releases are not in the repository, so the dev version number created by BOSH in the Concourse container will always be 1 (foobar-sha1-5+dev.1.yml). So just to make it sure, I would use the current timestamp instead of auto increasing the last dev version number, what makes no sense in Concourse.

**Comment by gogolok** [comment]
Thanks for the explanation. Such things should be documented. Either permanently in a README or the commit description (beginning with line 3), right?

**Comment by mlieser** [comment]
I decided to adjust the commit description because of the missing README. I know we should create a README at some point :)

**Pull request merged**
